services:
  postgres:
    user: root
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db
    volumes:
      - comp3000:/var/lib/postgresql/data

  pgadmin4:
    user: root
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - comp3000:/var/lib/postgresql/data
      - comp3000:/var/lib/pgadmin

volumes:
  comp3000:
