services:
  postgres:
    user: root
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db
    volumes:
      - comp3000:/var/lib/postgresql/data

  pgadmin4:
    user: root
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - comp3000:/var/lib/postgresql/data
      - comp3000:/var/lib/pgadmin

  mailslurper:
    image: derekahn/mailslurper
    ports:
      - 2500:2500
      - 8080:8080
      - 8085:8085

volumes:
  comp3000:

  # mailcow:
  #   user: root
  #   image: mailcow/dovecot
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "25:25"
  #     - "110:110"
  #     - "143:143"
  #     - "465:465"
  #     - "587:587"
  #     - "993:993"
  #     - "995:995"

  # mailhog:
  #   user: root
  #   image: mailhog/mailhog
  #   ports:
  #     - "8025:8025"
  #     - "1025:1025"
  #   environment:
  #     MH_STORAGE: "maildir"
  #     MH_MAILDIR_PATH: "/var/lib/mailhog"
  #   volumes:
  #     - comp3000:/var/lib/mailhog
