services:
  postgres:
    user: ${COMPOSEUSER}
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRESPASS}
      POSTGRES_USER: ${POSTGRESUSER}
      POSTGRES_DB: db
    volumes:
      - comp3000:/var/lib/postgresql/data

  pgadmin4:
    user: ${COMPOSEUSER}
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMINUSER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMINPASS}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - comp3000:/var/lib/postgresql/data
      - comp3000:/var/lib/pgadmin

volumes:
  comp3000:
